# Setup
title: Gymnasium Static Content
url: https://staging.thegymcms.com
gymurl: https://courses.gymna.si
aqassetsurl: https://assets.aquent.com
timezone: America/New_York
environment: staging
banner: true

# Building

exclude:
  - 'docker-compose.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'netlify.toml'
  - '.jekyll-cache'
  - 'local'

include:
  - '_redirects'

repository: gymnasium/gymcms

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false

## CSS Preprocessing/SASS (see @https://github.com/jekyll/jekyll-sass-converter)
sass:
  sass_dir: _sass
  style: compressed
  
## Additional Plugins
plugins:
  - jekyll-get-json

## JSON Fetch
jekyll_get_json:
  - data: jobs
    json: 'https://stag-assets.aquent.com/apps/gym/jobs.json?limit=1500'
  - data: markets
    json: 'https://stag-assets.aquent.com/apps/gym/markets.json'
  - data: privacy-index
    json: 'https://assets.aquent.com/api/content/render/false/type/json/query/+contentType:webPageContent%20+webPageContent.title:*privacy-policy-index*%20+languageId:1%20+deleted:false%20+working:true/'
  - data: privacy-shield-notice
    json: 'https://assets.aquent.com/api/content/render/false/type/json/query/+contentType:webPageContent%20+webPageContent.title:*privacy-policy-privacy-shield-notice*%20+languageId:1%20+deleted:false%20+working:true/'
  - data: privacy-ccpa
    json: 'https://assets.aquent.com/api/content/render/false/type/json/query/+contentType:webPageContent%20+webPageContent.title:*privacy-policy-ccpa-policy*%20+languageId:1%20+deleted:false%20+working:true/'
  - data: privacy-data-category
    json: 'https://assets.aquent.com/api/content/render/false/type/json/query/+contentType:webPageContent%20+webPageContent.title:*privacy-policy-data-category*%20+languageId:1%20+deleted:false%20+working:true/'
  - data: privacy-eu-rights
    json: 'https://assets.aquent.com/api/content/render/false/type/json/query/+contentType:webPageContent%20+webPageContent.title:*privacy-policy-european-rights*%20+languageId:1%20+deleted:false%20+working:true/'

