# Setup
title: Gymnasium Static Content
url: https://staging.gymcms.xyz
baseurl:
timezone: America/New_York


collections:
  take5s:
    output: true
    sort_by: topic
    permalink: /static/take5/:name
    
# Building

exclude:
  - 'docker-compose.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'netlify.toml'

repository: gymnasium/gymcms

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false
