# Setup
title: Gymnasium Static Content
url: https://dev--gymcms.netlify.com
baseurl:
timezone: America/New_York
environment: development


collections:
    webinars:
        output: true
        permalink: /static/webinars/

# Building

exclude:
  - 'docker-compose.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'netlify.toml'

repository: gymnasium/gymcms

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false
