version: '3.2'
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --config _local_config.yml
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
      - .:/srv/jekyll
