version: '3.2'
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --incremental --force_polling
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
      - .:/srv/jekyll
