[[headers]]
  for = "/favicon/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/feeds/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "*.js"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.(svg|jpg|jpeg|png|gif|webp|ico|ttf|ttc|otf|eot|woff|woff2)"
  [headers.values] # cache for 1 year
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[build]
edge_functions = ".netlify/functions"

# [[edge_functions]]
#   function = "og"
#   path = "/og-image"

[[edge_functions]]
  function = "test"
  path = "/test"

# [functions."og"]
#   included_files = ["fonts/brandon_bld-webfont.woff","_data/courses/**.yml", "_data/take5/**.yml", "_data/workshops/**.yml", "_data/webinars/**.yml"]

# [functions."test"]
#   included_files = ["fonts/brandon_bld-webfont.woff","_data/courses/**.yml", "_data/take5/**.yml", "_data/workshops/**.yml", "_data/webinars/**.yml"]

# dev branch build
# https://dev--gymcms.netlify.com/
[context.dev]
  command = "JEKYLL_ENV=development bundle exec jekyll build --config _dev_config.yml"

[context.dev.processing.images]
  compress = true
[context.dev.processing.css]
  minify = true
[context.dev.processing.js]
  minify = true

# staging branch build
# https://staging.thegymcms.com/
[context.staging]
  command = "JEKYLL_ENV=staging bundle exec jekyll build"

[context.staging.processing.images]
  compress = true
[context.staging.processing.css]
  minify = true
[context.staging.processing.js]
  minify = true

# Deploy preview build
[context.deploy-preview]
  command = "printf \"url: %s\" \"$DEPLOY_PRIME_URL\" > _config_netlify.yml; JEKYLL_ENV=staging bundle exec jekyll build --config _config.yml,_config_netlify.yml"

[context.deploy-preview.processing]
  skip_processing = true

# production branch build
# https://thegymcms.com/
[context.production]
  command = "JEKYLL_ENV=production bundle exec jekyll build --config _production_config.yml"

[context.production.processing.images]
  compress = true
[context.production.processing.css]
  minify = true
[context.production.processing.js]
  minify = true
