meta: 
  title: Aquent Gymnasium
  subtitle: 
  author: Gymnasium
  description: Design a career you love with free online courses on design, development, accessibility, prototyping, UX, and career skills.
  og_img: /img/brand/og/gym-brand-og.png
  twitter_handle: "@AquentGymnasium"
navigation:
  main:
  - title: About
    href: /about/
  - title: Courses
    href: /courses/
  - title: Tutorials
    href: /tutorials/
  - title: Webinars
    href: /webinars/
  - title: Instructors
    href: /instructors/
  - title: Blog
    href: /blog/
  footer:
  - title: What We Do
    links:
      - title: Courses
        href: /courses/
      - title: Tutorials
        href: /courses/take5/
      - title: Jobs
        href: /jobs/
      - title: Webinars
        href: /webinars/
      - title: Articles
        href: https://medium.com/gymnasium
        target: _blank
        rel: noopener
      - title: About
        href: /about/
  - title: Content Collections
    links:
      - title: Design Systems
        href: /design-systems/
      - title: Web Development
        href: /web-development/
      - title: UX Design
        href: /ux-design/
      - title: Prototyping
        href: /prototyping/
      - title: Accessibility
        href: /accessibility/
      - title: Remote Work
        href: /remote-work/
  - title: Resources
    links:
      - title: FAQ
        href: /faq/
      - title: Support
        href: /support/
      - title: Social Impact
        href: /social-impact/
      - title: Privacy Policy
        href: /privacy-policy/
      - title: Corporate Social Responsibility
        href: https://aquent.com/csr-policy
        target: _blank
        rel: noopener
      - title: Impressum
        href: https://aquent.de/impressum
        target: _blank
        rel: noopener
  - title: Social
    links:
      - title: Twitter
        href: https://twitter.com/AquentGymnasium
      - title: Facebook
        href: https://www.facebook.com/aquentgymnasium/
      - title: Instagram
        href: https://www.instagram.com/aquent_gymnasium/
      - title: YouTube
        href: https://www.youtube.com/channel/UCsAAa0dL-ZJpq4gN1zEcXYw
      - title: LinkedIn
        href: https://www.linkedin.com/school/gymnasium/
      - title: Medium
        href: https://medium.com/gymnasium
      - title: Github
        href: https://github.com/gymnasium
      - title: TikTok
        href: https://tiktok.com/@aquentgymnasium
  - title: Affiliated Sites
    links:
      - title: Aquent
        href: https://aquent.com
        target: _blank
        rel: noopener
      - title: Aquent Talent
        href: https://aquenttalent.com
        target: _blank
        rel: noopener
      - title: Aquent Studios
        href: https://aquentstudios.com
        target: _blank
        rel: noopener
      - title: Aquent RoboHead
        href: https://www.robohead.net
        target: _blank
        rel: noopener
      - title: Aquent Scout
        href: https://aquentscout.com
        target: _blank
        rel: noopener
feeds:
  - blog: https://medium.com/feed/gymnasium

