name: Broken link check
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - 'feature/**'
      - 'bug/**'
      - 'patch/**'
  # pull_request:
  #   branches:
  #     - staging
  #     - production

jobs:
  # broken_link_checker_job:
  #   runs-on: ubuntu-latest
  #   name: broken-link-check
  #   steps:
  #   - name: broken-link-check
  #     id: link-report
  #     uses: ScholliYT/Broken-Links-Crawler-Action@v3
  #     with:
  #       website_url: 'https://courses.gymna.si'
  #       resolve_before_filtering: 'true'
  #       include_url_contained: 'thegymnasium.com,courses.gymna.si,thegymcms.com'
  #       exclude_url_prefix: 'mailto:,tel:'
  #       exclude_url_contained: 'linkedin.com,twitter.com,facebook.com,instagram.com,medium.com,/login?next='
  #       verbose: 'error' # true/false/yes/no/on/off/debug/info/warning/error/critical
  #       max_retry_time: 30
  #       max_retries: 5
  #       max_depth: -1 # -1 = unlimited depth (default -1)
  #       connect_limit_per_host: 10 # default
  #   - name: get-result
  #     run: echo "${{steps.link-report.outputs}}"
  # my-broken-link-checker:
  #   name: Check broken links
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check
  #       uses: ruzickap/action-my-broken-link-checker@v2.2.3
  #       with:
  #         url: https://courses.gymna.si
  #         cmd_params: "--buffer-size=8192 --max-connections=10 --max-connections-per-host=10 --color=always --rate-limit=10 --timeout=120 --ignore-fragments --exclude=.*(facebook|instagram|twitter|medium|linkedin|google|vitamintalent|apple)\\.(com)|(\\/login\\?next.*)$"
  #         run_timeout: 600
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: "https://courses.gymna.si/**/*" --verbose --exclude=.*(facebook|instagram|twitter|medium|linkedin|google|vitamintalent|apple|doubleclick)\\.(com|net)|(\\/login\\?next.*)$ --headers "accept=text/html"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
        
      # - name: Create Issue From File
      #   uses: peter-evans/create-issue-from-file@v2
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
