name: Broken link check
on:
  # Trigger the workflow on push for specific branches
  push:
    branches:
      - 'feature/**'
      - 'bug/**'
      - 'patch/**'
  # pull_request:
  #   branches:
  #     - staging
  #     - production

jobs:
  # my-broken-link-checker:
  #   name: Check broken links with Muffet
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check
  #       uses: ruzickap/action-my-broken-link-checker@v2.2.3
  #       with:
  #         url: https://courses.gymna.si
  #         cmd_params: --buffer-size=8192 --max-connections=10 --skip-tls-verification --max-connections-per-host=10 --color=always --rate-limit=10 --timeout=120 --ignore-fragments --max-redirections=128 --exclude=".*(facebook|instagram|twitter|medium|linkedin|google|vitamintalent|apple)\\.(com)|(\\/login\\?next.*)$" --header="Accept:*/*"
  #         run_timeout: 600

  check-broken-links:
    runs-on: ubuntu-latest
    steps:
    - name: Check links with Muffet alt
      uses: mattorb/actions-muffet@v1.3.1
      with: 
        args: >
          --timeout 300
          https://courses.gymna.si


  # --exclude ".*(facebook|instagram|twitter|medium|linkedin|google|vitamintalent|apple)\\.(com)|(\\/login\\?next.*)$
  # --skip-tls-verification
  # --color=always
  # --ignore-fragments

  # linkChecker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Link Checker
  #       uses: lycheeverse/lychee-action@v1.0.8
  #       with:
  #         args: https://courses.gymna.si/**/* --verbose --exclude=.*(facebook|instagram|twitter|medium|linkedin|google|vitamintalent|apple|doubleclick)\\.(com|net)|(\\/login\\?next.*)$ --headers "accept=text/html"
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #     - name: Fail if there were link errors
  #       run: exit ${{ steps.lychee.outputs.exit_code }}
        
      # - name: Create Issue From File
      #   uses: peter-evans/create-issue-from-file@v2
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
