name: Broken link check
on:
  # Trigger the workflow on push for specific branches
  push:
    branches:
      - 'feature/**'
      - 'bug/**'
      - 'patch/**'
  # pull_request:
  #   branches:
  #     - staging
  #     - production

jobs:
  ## Linkinator uses the linkinator.config.json file for additional options
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator-action@v1.5.4
        with:
          paths: https://courses.gymna.si


  # linkChecker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Link Checker
  #       uses: lycheeverse/lychee-action@v1.0.8
  #       with:
  #         args: https://courses.gymna.si/**/* --verbose --exclude=.*(facebook|instagram|twitter|medium|linkedin|google|vitamintalent|apple|doubleclick)\\.(com|net)|(\\/login\\?next.*)$ --headers "accept=text/html"
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #     - name: Fail if there were link errors
  #       run: exit ${{ steps.lychee.outputs.exit_code }}
        
      # - name: Create Issue From File
      #   uses: peter-evans/create-issue-from-file@v2
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
