name: Broken link check
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - 'feature/**'
      - 'bug/**'
      - 'patch/**'
  pull_request:
    branches:
      - staging
      - production

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: broken-link-check
    steps:
    - name: broken-link-check
      id: link-report
      uses: ScholliYT/Broken-Links-Crawler-Action@v3
      with:
        website_url: 'https://courses.gymna.si'
        exclude_url_prefix: 'mailto:,tel:'
        exclude_url_contained: 'linkedin.com,twitter.com,facebook.com,instagram.com,medium.com,/login?next='
        verbose: 'true' # true/false/yes/no/on/off/debug/info/warning/error/critical
        max_retry_time: 30
        max_retries: 5
        max_depth: -1 # -1 = unlimited depth (default -1)
        connect_limit_per_host: 10 # default
    - name: get-result
      run: echo "${{steps.link-report.outputs.result}}"
